name: kalibre_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  google_sign_in: ^6.1.3
  flutter_screenutil: ^5.7.0
  google_fonts: ^5.1.0
  clay_containers: ^0.3.2
  flutter_svg: ^2.0.5
  lottie: ^2.3.2
  email_validator: ^2.1.17
  fluttertoast: ^8.2.2
  connectivity_plus: ^3.0.4
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_logo.jpeg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
